version: "3"

services:
    web:
      image: nginx:latest
      volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./:/opt/app
      ports:
        - "8087:80"
      depends_on:
        - app
    app:
      build: .
      volumes:
        - ./:/opt/app
      depends_on:
        - db
    db:
      image: mysql:latest
      ports:
        - "33062:3306"
      environment:
         MYSQL_ROOT_PASSWORD: "root"