version: "3"

services:
    web:
      image: nginx:latest
      restart: unless-stopped
      volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8087:80"
      depends_on:
        - app
    app:
      build: .
      restart: unless-stopped
      volumes:
        - ./:/opt/app
      depends_on:
        - db
    db:
      image: mysql:5.5
      restart: unless-stopped
      volumes:
        - "mysql-data:/var/lib/mysql"
      ports:
        - "33062:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root

volumes:
    mysql-data: